// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-qxXpsMwO6mGfJxTAHRI0KvJYt8itIw',
    appId: '1:47494083713:web:de5b2b2caea52d6d2f0980',
    messagingSenderId: '47494083713',
    projectId: 'recklamradar-98889',
    authDomain: 'recklamradar-98889.firebaseapp.com',
    storageBucket: 'recklamradar-98889.firebasestorage.app',
    measurementId: 'G-JKDN70DN63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJ_hGg07GKK3_J-rnnlFahdBg2LazP1I',
    appId: '1:47494083713:android:21f38a1b2b922cf12f0980',
    messagingSenderId: '47494083713',
    projectId: 'recklamradar-98889',
    storageBucket: 'recklamradar-98889.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyN8pGX8s2eCX5BzdkzXhg2DK-2kG7ws',
    appId: '1:47494083713:ios:1eab55f8eceb1cc32f0980',
    messagingSenderId: '47494083713',
    projectId: 'recklamradar-98889',
    storageBucket: 'recklamradar-98889.firebasestorage.app',
    iosClientId: '47494083713-3tmbo69bte3ni595ta0n7la9u0f9ba72.apps.googleusercontent.com',
    iosBundleId: 'com.example.recklamradar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqyN8pGX8s2eCX5BzdkzXhg2DK-2kG7ws',
    appId: '1:47494083713:ios:1eab55f8eceb1cc32f0980',
    messagingSenderId: '47494083713',
    projectId: 'recklamradar-98889',
    storageBucket: 'recklamradar-98889.firebasestorage.app',
    iosClientId: '47494083713-3tmbo69bte3ni595ta0n7la9u0f9ba72.apps.googleusercontent.com',
    iosBundleId: 'com.example.recklamradar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-qxXpsMwO6mGfJxTAHRI0KvJYt8itIw',
    appId: '1:47494083713:web:0d30605365ef463c2f0980',
    messagingSenderId: '47494083713',
    projectId: 'recklamradar-98889',
    authDomain: 'recklamradar-98889.firebaseapp.com',
    storageBucket: 'recklamradar-98889.firebasestorage.app',
    measurementId: 'G-BQV1QJ8EJV',
  );

}